fancier/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'fancier'

urlpatterns = [
    url(r'^$' , views.fancier_list , name="list"),
    url(r'^new/' , views.new_fancier , name="new"),
    path('<slug:slug>/' , views.fancier_details , name= 'details'),
]

pigeon/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'pigeon'

urlpatterns = [
    url(r'^$' , views.pigeons_list , name='list'),
    path('<slug:slug>/',views.pigeon_details , name = "details"),
]

wingspedigree/urls.py
from django.contrib import admin
from django.urls import path
from django .conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^fancier/' , include('fancier.urls')),
    url(r'^pigeon/', include('pigeon.urls'))
]

urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT )

fancier/models.py
from django.db import models

class Fancier(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    #birthDate = models.DateField(auto_now = True , auto_now_add=False)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    region = models.CharField(max_length =30)
    street = models.CharField(max_length = 100)
    joinedDate = models.DateTimeField(auto_now_add=True)
    profilePicture = models.ImageField(default = 'defaultfancier.png' , blank = True)

    def __str__(self):
        return self.name

pigeon/models.py
from django.db import models
from fancier.models import Fancier

class Pigeon(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=15)
    sex = models.CharField(max_length=1)
    birthYear = models.CharField(max_length=6)
    ringNumber = models.CharField(max_length=20 , unique=True)
    father = models.ForeignKey('self' , null=True , default=None  , blank = True, related_name='pigeonFather', on_delete = models.PROTECT)
    mother = models.ForeignKey('self' , null=True , default=None ,  blank = True,related_name='pigeonMother' , on_delete=models.PROTECT)
    fancier = models.ForeignKey(Fancier , default=None , on_delete = models.PROTECT)
    thumb = models.ImageField(default = 'defaultpigeon.png', blank = True)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name


fancier/forms.py
from django import forms
from . import models


class NewFancier(forms.ModelForm):
    class Meta:
        model = models.Fancier
        fields = ['name' , 'slug' ,  'country' , 'state' , 'city',
                        'region' , 'street' , 'profilePicture']

fancier/views.py
from django.shortcuts import render,redirect
from . models import Fancier
from . import forms


#Create new Fancier
def new_fancier(request):
    if request.method == 'POST':
        form = forms.NewFancier(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            return redirect('fancier:list')
    else:
        form = forms.NewFancier()
    return render(request , 'fancier/new_fancier.html' , {'form':form})


#Show all fanciers
def fancier_list(request):
    fanciers = Fancier.objects.all().order_by('joinedDate')
    return render(request , 'fancier/fancier_list.html' , {'fanciers':fanciers})

#Show specific Fancier details
def fancier_details(request , slug):
    fancier = Fancier.objects.get(slug = slug)
    return render(request , 'fancier/fancier_details.html' , {'fancier':fancier})

pigeon/views.py
from django.shortcuts import render
from . models import Pigeon

#Show All Pigeons
def pigeons_list(request):
    pigeons = Pigeon.objects.all()
    return render(request , 'pigeon/pigeons_list.html', {'pigeons':pigeons})


#Show specific Pigeon detaisl in single page
def pigeon_details(request , slug):
    pigeon = Pigeon.objects.get(slug=slug)
    return render(request , 'pigeon/pigeon_details.html' , {'pigeon':pigeon})

fancier/templates/fancier/fancier_details.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="fancier_details">
        <div class="fancier">
            <img src="{{ fancier.profilePicture.url }}" width="250" height="150"/>
            <h3>{{fancier.name}}</h3>
            <p><i>Country:</i>{{fancier.country}}</p>
            <p><i>State:</i> {{fancier.state}} </p>
            <p><i>City:</i> {{fancier.city}} </p>
            <p><i>Region: </i> {{fancier.region}} </p>
            <p><i>Joined Date: </i> {{fancier.joinedDate}} </p>
        </div>
    </div>

{% endblock %}

fancier/templates/fancier/fancier_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <di class="fanciers">
        {% for fancier in fanciers %}
            <div class="fancier">
                <img src="{{fancier.profilePicture.url}}" width="200" height="150"/>
                <h4><a href="{% url 'fancier:details' slug=fancier.slug %}">{{fancier.name}}</a></h4>
                <p>Country : {{fancier.country}}</p>
                <p>Join Date : {{fancier.joinedDate}}</p>
            </div>
        {% endfor %}
    </di>

{% endblock %}    

fancier/templates/fancier/new_fancier.html
{% extends 'base_layout.html' %}

{% block content%}

    <div class="new_fancier">
        <h2>Add New Fancier</h2>
        <form class="site-form" action="{% url 'fancier:new' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create"/>

        </form>
    </div>

{% endblock %}

pigeon/templates/pigeon/pigeon_details.html
{% extends 'base_layout.html' %}

{% block content %}

    <div class="pigeon-details">
        <div class="pigeon">
            <img src="{{ pigeon.thumb.url }}" width="500" height="400"/>
            <h2>{{ pigeon.name }}</h2>
            <p><b>Ring Number: </b> {{ pigeon.ringNumber }}</p>
            <p><b>Birth Year: </b> {{pigeon.birthYear}}</p>
            <p><b>Fancier: </b> {{pigeon.fancier}}</p>
            <p><b>Father: </b> {{pigeon.father}}</p>
            <p><b>Mother: </b> {{pigeon.mother}}</p>
        </div>
    </div>

{% endblock %}

pigeon/templates/pigeon/pigeons_list.html
{% extends 'base_layout.html' %}
{% block content %}

    <div class="pigeons">
        {% for pigeon in pigeons %}
            <div class="pigeon" style="display: inline-block; text-align: center;">
                <img src="{{ pigeon.thumb.url }}" width="250" height="200"/>
                <a href="{% url 'pigeon:details' slug=pigeon.slug %}"> <p><b>Pigeon name: </b>{{pigeon.name}} </p> </a>
                <p><b>Ring Number:</b>{{pigeon.ringNumber}}</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/base_layout.html
{% load static  %}
<!DOCTYPE html>
<html>

    <head>
        <title>Wings Pedigree</title>
        

    </head>

    <body>

        <div class="wrapper">

          {% block content %}

          {% endblock %}

        </div>


    </body>

</html>